export default {
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  mutate: [
    "src/domain/**/*.ts",
    "src/app-server/protocol/**/*.ts",
    "src/features/chat/domain/**/*.ts",
    "src/features/chat/app-server/mappers/thread-stream/**/*.ts",
    "src/features/chat/application/state/**/*.ts",
    "src/features/chat/application/turns/**/*.ts",
    "src/features/chat/application/pending-requests/**/*.ts",
    "src/features/chat/application/submission/optimistic-turn-start.ts",
    "src/features/chat/application/submission/turn-submission-plan.ts",
    "src/app-server/query/{active-thread-inventory,invalidated-query-refresh,snapshots}.ts",
    "src/features/chat/app-server/adapters/thread-reference-resolver.ts",
    "src/features/threads/workflows/**/*.ts",
    "src/shared/async/**/*.ts",
    "src/settings/preferences.ts",
    "src/features/selection-rewrite/{model,session}.ts",
  ],
  ignoreStatic: true,
  incremental: true,
  reporters: ["clear-text", "progress", "html"],
};
