export default {
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  // Local history and generated reports are not test inputs.
  ignorePatterns: ["/.jj", "/coverage"],
  mutate: [
    "src/domain/**/*.ts",
    "src/app-server/protocol/**/*.ts",
    "src/features/chat/domain/**/*.ts",
    "src/features/chat/app-server/**/*.ts",
    "src/features/chat/application/*.ts",
    "src/features/chat/application/state/**/*.ts",
    "src/features/chat/application/turns/**/*.ts",
    "src/features/chat/application/pending-requests/**/*.ts",
    "src/features/chat/application/composer/**/*.ts",
    "src/features/chat/application/submission/**/*.ts",
    "src/features/chat/application/threads/**/*.ts",
    "src/app-server/query/**/*.ts",
    "src/features/threads/workflows/**/*.ts",
    "src/shared/async/**/*.ts",
    "src/settings/*.ts",
    "src/features/selection-rewrite/**/*.ts",
    "!src/**/*.dom.ts",
    "!src/**/*.obsidian.ts",
  ],
  ignoreStatic: true,
  incremental: true,
  reporters: ["clear-text", "progress", "html"],
};
